package br.unisinos.omniphr.middleware.datablock;

import br.unisinos.omniphr.core.Datablock;
import br.unisinos.omniphr.net.NetworkEnvironment;
import br.unisinos.omniphr.p2p.chord.ChordNode;
import br.unisinos.omniphr.p2p.chord.Hops;
import br.unisinos.omniphr.p2p.pubsub.PubSubMessage;
import br.unisinos.omniphr.p2p.pubsub.PubSubService;

import java.util.List;

/**
 * Nodes Manager component of the Datablock and Service Module. Manages and
 * controls the input and output of regular (leaf) and routing overlay nodes
 * in the network, promoting scalability and load balancing. Node entry and
 * exit follow the rules of the adopted DHT algorithm: when a node wishes to
 * be inserted, this component generates a new identifier for it and notifies
 * the other nodes that it is accessible; when a node enters or leaves, the
 * routing overlay is notified and decides whether copies must be
 * disseminated.
 */
public class NodesManager {

    public static final String TOPIC_NODES = "omniphr/nodes";

    private final NetworkEnvironment network;
    private final PubSubService pubSub;
    private final String overlayName;

    public NodesManager(NetworkEnvironment network, PubSubService pubSub, String overlayName) {
        this.network = network;
        this.pubSub = pubSub;
        this.overlayName = overlayName;
    }

    /**
     * Inserts a node into the network: the identifier is generated by the
     * DHT algorithm (consistent hash of the node name inside
     * {@link ChordNode}), the node joins the ring and the other nodes are
     * notified that it is accessible.
     */
    public void join(ChordNode node, ChordNode bootstrap) {
        network.register(node);
        if (bootstrap == null || bootstrap == node) {
            node.create();
        } else {
            node.join(bootstrap);
        }
        pubSub.publish(TOPIC_NODES, new PubSubMessage(PubSubMessage.Type.NODE_JOINED,
                overlayName, node.getName(), "id=" + node.getId()));
    }

    /**
     * Graceful output of a node. The replicas handed over by the leaving
     * node are re-disseminated through the DHT by the routing overlay.
     */
    public void leave(ChordNode node, Distributor distributor) {
        List<Datablock> handedOver = node.leave();
        network.unregister(node);
        for (Datablock block : handedOver) {
            distributor.replicate(block, new Hops());
        }
        pubSub.publish(TOPIC_NODES, new PubSubMessage(PubSubMessage.Type.NODE_LEFT,
                overlayName, node.getName(), "replicas re-disseminated: " + handedOver.size()));
    }

    /**
     * Periodic maintenance round of the Chord algorithm over all alive
     * nodes: stabilization, notification and finger fixing, so the control
     * tables automatically adjust to nodes entering and leaving.
     */
    public void stabilizationRound() {
        for (ChordNode n : network.allNodes()) {
            if (n.isAlive()) {
                n.stabilize();
                n.fixFingers();
            }
        }
    }

    /** Simple load-balancing report: replicas per node. */
    public String loadReport() {
        StringBuilder sb = new StringBuilder();
        int total = 0, alive = 0;
        for (ChordNode n : network.allNodes()) {
            if (n.isAlive()) {
                alive++;
                total += n.getStore().size();
            }
        }
        sb.append(alive).append(" alive nodes, ").append(total).append(" stored replicas, avg ")
                .append(alive == 0 ? 0 : String.format("%.1f", (double) total / alive))
                .append(" replicas/node");
        return sb.toString();
    }
}
